config/routes.rb
ESurvey::Application.routes.draw do
  #ADMIN PANEL
  namespace :manage do
    controller :home do
      get :index
    end

    resources :surveys, :questions
    resources :users

    root :to => 'home#index'
  end

  controller :pages do
    get :welcome
    get :about
    get :instruction
    get :survey_results
    get :db_populate
  end

  mount Surveyor::Engine => "/surveys", :as => "surveyor"

  root :to => 'pages#welcome'
end

app/views/shared/_flash_messages.html.haml
- flash.each do |type, message|
  %div{:class => "alert alert-#{{:notice => :info, :alert => :error}[type] || type}"}
    %a.close{:"data-dismiss" => "alert"}
      &times;
    = message

app/views/shared/_footer.html.haml
.footer
  .container
    #footer-line
      .pull-left
        = link_to 'About', about_path
        |
        = link_to 'Instruction', instruction_path

      .pull-right
        Copyright © #{Date.today.year}

app/views/shared/_form_error.html.haml
- if obj.errors.any?
  .alert.alert-block.alert-error
    %a.close{:"data-dismiss" => "alert"} &times;
    - obj.errors.full_messages.each do |message|
      %p= message

app/views/shared/_nav.html.haml
.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to "e-survey", root_path, {:class => 'brand'}

      .container.nav-collapse
        %ul.nav.pull-right
          %li= link_to 'Populate Fake Data', '/db_populate' if Survey.count < 35
          %li= link_to 'Take a Survey', '/surveys'
          %li.dropdown.pjax-links
            %a.dropdown-toggle{:href => "javascript:void(0);", "data-toggle" => "dropdown"}
              Admin
              %b.caret
            %ul.dropdown-menu
              %li= link_to 'Users', manage_users_path
              %li= link_to 'New user', new_manage_user_path
              %li.divider
              %li= link_to 'Surveys', manage_surveys_path
              %li.divider
              %li= link_to 'Survey Results', survey_results_path