config/routes.rb
ESurvey::Application.routes.draw do
  #ADMIN PANEL
  namespace :manage do
    controller :home do
      get :index
    end

    resources :surveys, :questions
    resources :users

    root :to => 'home#index'
  end

  controller :pages do
    get :welcome
    get :about
    get :instruction
    get :survey_results
    get :db_populate
  end

  mount Surveyor::Engine => "/surveys", :as => "surveyor"

  root :to => 'pages#welcome'
end

app/views/pages/about.html.haml
.container
  .hero-unit
    %h2 Morshed Alam

    %h6
      %span.label.label-info Email:
      %a{:href => "mailto:morshed201@gmail.com", :target => "_blank"} morshed201@gmail.com

    %h6
      %span.label.label-info Website:
      %a{:href => "http://morshed-alam.com", :target => "_blank"} http://morshed-alam.com

app/views/pages/instruction.html.haml
%h3 Populate Sample Data
%p
  %code
    bundle exec rake db:populate
%br

%h3 Take a Survey
%h5{:style => "font-weight:normal"}
  %p
    1. Click to
    %span.label.label-info Take a Survey
    link from navigation bar
  %p
    2. System will show all the surveys available in the system with questions and results count respectively
    %span.label.label-info Q : 10
    %span.label.label-info R : 10

  %p
    2. Click any boxes to take survey

%br
%h3 Selecting User
%h5{:style => "font-weight:normal"}
  System automatically selecting a random user from database and instantiate survey page.

%br
%h3 Contributing
%p 1. Fork it
%p 2. Create your feature branch (`git checkout -b my-new-feature`)
%p 3. Commit your changes (`git commit -am 'Added some feature'`)
%p 4. Push to the branch (`git push origin my-new-feature`)
%p 5. Create new Pull Request

app/views/pages/survey_results.html.haml
%h4 Survey Result

- if @response_sets.any?
  %table.table.table-striped
    %thead
      %tr
        %th Title
        %th User
        %th.center #Questions
        %th.date Date
        %th.actions

    %tbody
      - @response_sets.each do |response_set|
        %tr
          %td= link_to(response_set.survey.title, manage_survey_path(response_set.user))
          %td= link_to(response_set.user.name, manage_user_path(response_set.user))
          %td.center= response_set.survey.question_count
          %td= show_date(response_set.updated_at)
          %td.actions
            - details = surveyor.view_my_survey_path(:survey_code => response_set.survey.access_code,
            :response_set_code => response_set.access_code)
            = link_to('Show', details, :class => 'btn btn-mini')

- else
  .empty No survey result found.

app/views/pages/welcome.html.haml
.container
  .hero-unit
    %h2 Welcome to e-survey
    %p
      Please make sure to add
      = link_to 'User', manage_users_path()
      ,
      = link_to 'Survey', manage_surveys_path()
      and
      = link_to 'Question', manage_questions_path()
      to take a survey...